### ISSUE TITLE
New Errors since updating

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/Impulcifer#35]
Wanted to run a few new recordings, updated the repo.

Followed the guide on the wiki as usual but now getting the following error. I've not run any plots and even when I add the plot switch, there's still an error. But when I create a blank headphones.png the HRIR outputs fine.

```
(venv) c:\Users\dushy\Impulcifer>python impulcifer.py --test_signal="data/sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl" --dir_path="data/my_hrir" --no_room_correction
Traceback (most recent call last):
  File "impulcifer.py", line 422, in <module>
    main(**create_cli())
  File "impulcifer.py", line 91, in main
    compensate_headphones(headphones, hrir, dir_path=dir_path)
  File "impulcifer.py", line 344, in compensate_headphones
    fig.savefig(os.path.join(dir_path, 'plots', 'Headphones.png'))
  File "C:\Users\dushy\Impulcifer\venv\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\dushy\Impulcifer\venv\lib\site-packages\matplotlib\backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "C:\Users\dushy\Impulcifer\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "c:\users\dushy\appdata\local\programs\python\python37\Lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\dushy\Impulcifer\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "C:\Users\dushy\Impulcifer\venv\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\dushy\\Impulcifer\\data\\my_hrir\\plots\\Headphones.png'
```

**Comment by jaakkopasanen** [comment]
Interesting. When you create the blank Headphones.png file does Impulcifer overwrite that with the actual headphone frequency response graph?

What operating system and Python version are you running?

**Comment by arkserg** [comment]
Oh, I got that error too, but forget to report it, sorry. I was running windows 10 x64. Created plots folder manually and the problem was gone.

**Comment by jaakkopasanen** [comment]
Sounds like I forgot to add or move the plots folder creation. Thanks for the tip.

**Comment by jaakkopasanen** [comment]
I might have fixed this now. I moved headphone plots to before HRIR processing and that now includes plots folder creation. Could either of you test if the issue has been solved?

**Comment by arkserg** [comment]
Works fine now.
