### ISSUE TITLE
Error with --help Verify installation

### ISSUE THREAD

**Issue by venkatesh63** [jaakkopasanen/Impulcifer#37]
(venv) C:\Program Files\EqualizerAPO\config\Impulcifer-master>python impulcifer.py --help
Traceback (most recent call last):
  File "impulcifer.py", line 9, in <module>
    from scipy import signal
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\signal\__init__.py", line 289, in <module>
    from . import sigtools, windows
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\signal\windows\__init__.py", line 41, in <module>
    from .windows import *
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\signal\windows\windows.py", line 9, in <module>
    from scipy import fftpack, linalg, special
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\linalg\__init__.py", line 213, in <module>
    from ._sketches import *
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\linalg\_sketches.py", line 11, in <module>
    from scipy.sparse import csc_matrix
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\sparse\__init__.py", line 230, in <module>
    from .csr import *
  File "C:\PROGRA~1\EQUALI~1\config\IMPULC~1\venv\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: DLL load failed: The specified module could not be found.

i got bad sectors in old disk i replaced to new hard drive.This are Fresh installation.And Python version i installed 3.7.4

**Comment by venkatesh63** [comment]
i git scipy problem i resolved with https://www.microsoft.com/en-in/download/details.aspx?id=48145 Visual C++ Redistributable for Visual Studio 2015.
