### ISSUE TITLE
Error, don't create hrir.wav

### ISSUE THREAD

**Issue by PhilHiTech** [jaakkopasanen/Impulcifer#39]
```
(venv) C:\ProgramsPortable\Impulcifer>python impulcifer.py --test_signal=D:\I\Impulcifer_Data\sweep-12.30s-48000Hz-24bit-2.93Hz-24000Hz.pkl --fs=96000 --dir_path=D:\I\Impulcifer_Data\my_hrir_01_48k
Traceback (most recent call last):
  File "impulcifer.py", line 489, in <module>
    main(**create_cli())
  File "impulcifer.py", line 94, in main
    plot=plot
  File "impulcifer.py", line 217, in correct_room
    fr = ir.frequency_response()
  File "C:\ProgramsPortable\Impulcifer\impulse_response.py", line 175, in frequency_response
    fr = FrequencyResponse(name='Frequency response', frequency=f[1::step], raw=m[1::step])
ValueError: slice step cannot be zero
```
 
Win10 x64, Python 3.7.5

**Comment by PhilHiTech** [comment]
I realized that I recorded the files for the calibration of the room in 2 channels ...
I solved by converting 2-channel wav files into a channel ...
