### ISSUE TITLE
New error after the last update, also in the demo

### ISSUE THREAD

**Issue by PhilHiTech** [jaakkopasanen/Impulcifer#44]
```
(venv) C:\ProgramsPortable\Impulcifer>python impulcifer.py --test_signal=D:\I\Impulcifer_Data\sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --room_mic_calibration=D:\I\Impulcifer_Data\demo\room-mic-calibration.txt --room_target=D:\I\Impulcifer_Data\room-target.csv --fs=96000 --dir_path=D:\I\Impulcifer_Data\demo --plot

Traceback (most recent call last):
  File "impulcifer.py", line 536, in <module>
    main(**create_cli())
  File "impulcifer.py", line 112, in main
    raw=0, error=0
  File "C:\ProgramsPortable\Impulcifer\venv\lib\site-packages\autoeq\frequency_response.py", line 76, in __init__
    self.raw = self._init_data(raw)
  File "C:\ProgramsPortable\Impulcifer\venv\lib\site-packages\autoeq\frequency_response.py", line 108, in _init_data
    data = [None if x is None or math.isnan(x) else x for x in data]
TypeError: 'int' object is not iterable
```

**Comment by PhilHiTech** [comment]
Sorry, I hadn't updated the Python components...
Everything works now.
