### ISSUE TITLE
When '--plot' option is exist, Error has occured.

### ISSUE THREAD

**Issue by kalstein00** [jaakkopasanen/Impulcifer#51]
normal use is not problem but, when I use --plot option, error has occured.

(venv) C:\Users\JHJ\Impulcifer>python impulcifer.py --test_signal=data\sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --dir_path=data\my_hrir
**<---- no error**

(venv) C:\Users\JHJ\Impulcifer>python impulcifer.py --test_signal=data\sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --dir_path=data\my_hrir --plot
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Traceback (most recent call last):
  File "impulcifer.py", line 499, in <module>
    main(**create_cli())
  File "impulcifer.py", line 121, in main
    fr.smoothen_heavy_light()
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\autoeq\frequency_response.py", line 1260, in smoothen_heavy_light
    treble_iterations=1
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\autoeq\frequency_response.py", line 1217, in smoothen_fractional_octave
    treble_f_upper=treble_f_upper
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\autoeq\frequency_response.py", line 1175, in _smoothen_fractional_octave
    y_normal = savgol_filter(y_normal, self._window_size(window_size), 2)
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\scipy\signal\_savitzky_golay.py", line 337, in savgol_filter
    coeffs = savgol_coeffs(window_length, polyorder, deriv=deriv, delta=delta)
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\scipy\signal\_savitzky_golay.py", line 139, in savgol_coeffs
    coeffs, _, _, _ = lstsq(A, y)
  File "C:\Users\JHJ\Impulcifer\venv\lib\site-packages\scipy\linalg\basic.py", line 1218, in lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares
**<---- Error!!**

Check it please.

**Comment by jaakkopasanen** [comment]
Apparently it's a bug in Windows: https://stackoverflow.com/a/64971496

Are you on Windows, 32-bit and/or AMD CPU?

As a workaround, you could use conda instead of virtualenv and pip.

**Comment by jaakkopasanen** [comment]
Plotting bug is probably now fixed in branch [plot-fix](https://github.com/jaakkopasanen/Impulcifer/tree/plot-fix). Switch from master with `git checkout plot-fix` and install dependencies `python -m pip install -U -r requirements.txt`. This comes with the requirement of Python 3.8 (up from 3.7).

@kalstein00 could you test if this solves the issue?

**Comment by jaakkopasanen** [comment]
Fixed by updating dependencies including Numpy 1.19.5 which has fix for the BLAS issue.
