### ISSUE TITLE
The error occurred while running recorder

### ISSUE THREAD

**Issue by 1781087246** [jaakkopasanen/Impulcifer#53]
Run with python3.75

(venv) C:\Users\17810\Impulcifer>python recorder.py --play="data/sweep-seg-FL,FR-stereo-6.15s-48000Hz-32bit-2.93Hz-24000Hz.wav" --record="data/my_hrir/headphones.wav"
Traceback (most recent call last):
  File "recorder.py", line 260, in <module>
    play_and_record(**create_cli())
  File "recorder.py", line 206, in play_and_record
    min_channels=n_channels
  File "recorder.py", line 135, in get_devices
    devices = sd.query_devices()
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in query_devices
    for i in range(_check(_lib.Pa_GetDeviceCount())))
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in <genexpr>
    for i in range(_check(_lib.Pa_GetDeviceCount())))
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by jaakkopasanen** [comment]
Which version of Python are you running? You can check it with `python --version`.

**Comment by 1781087246** [comment]
> 您正在运行哪个版本的Python？您可以使用进行检查`python --version`。

(venv) C:\Users\17810\Impulcifer>python --version
Python 3.7.5

**Comment by jaakkopasanen** [comment]
This seems to be a bug in sounddevice library and the bug was supposed to be fixed but apparently is not. https://github.com/spatialaudio/python-sounddevice/issues/72

You you happen to have some sound devices connected to your PC which have non-latin characters in their names?

Does `python -m sounddevice` work for you or does it crash too?

**Comment by 1781087246** [comment]
![~8VPLN71A9`B8AVJY58IXQ3](https://user-images.githubusercontent.com/73426385/97117171-ed33be80-173c-11eb-92f8-678ba180b402.png)
![~`681)`{6O_QZBFNP5~_FGC](https://user-images.githubusercontent.com/73426385/97117175-ef961880-173c-11eb-9922-b996b6e92590.png)

**Comment by 1781087246** [comment]
![image](https://user-images.githubusercontent.com/73426385/97117201-0fc5d780-173d-11eb-97dd-574bec23fc5b.png)

**Comment by 1781087246** [comment]
(venv) C:\Users\17810\Impulcifer>python -m sounddevice
Traceback (most recent call last):
  File "c:\users\17810\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\17810\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 2780, in <module>
    print(query_devices())
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in query_devices
    for i in range(_check(_lib.Pa_GetDeviceCount())))
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in <genexpr>
    for i in range(_check(_lib.Pa_GetDeviceCount())))
  File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 578, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by 1781087246** [comment]
> This seems to be a bug in sounddevice library and the bug was supposed to be fixed but apparently is not. [spatialaudio/python-sounddevice#72](https://github.com/spatialaudio/python-sounddevice/issues/72)
> 
> You you happen to have some sound devices connected to your PC which have non-latin characters in their names?
> 
> Does `python -m sounddevice` work for you or does it crash too?

(venv) C:\Users\17810\Impulcifer>python -m sounddevice
Traceback (most recent call last):
File "c:\users\17810\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\users\17810\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 2780, in
print(query_devices())
File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in query_devices
for i in range(_check(_lib.Pa_GetDeviceCount())))
File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 565, in
for i in range(_check(_lib.Pa_GetDeviceCount())))
File "C:\Users\17810\Impulcifer\venv\lib\site-packages\sounddevice.py", line 578, in query_devices
name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by 1781087246** [comment]
Thank you for your reminder, I am able to use UTF-8 after changing the language.
![image](https://user-images.githubusercontent.com/73426385/97123823-83c9a500-1768-11eb-8de6-02248da0d65e.png)

**Comment by 1781087246** [comment]
But i have a new problem

**Comment by 1781087246** [comment]
(venv) C:\Users\17810\Impulcifer>python impulcifer.py --test_signal=data\sweep-6.15s-48000Hz-32bit-2.93Hz-24000Hz.pkl --dir_path=data\my_hrir
Creating impulse response estimator...
Running room correction...
Running headphone compensation...
Creating headphone equalization...
Creating frequency response target...
Opening binaural measurements...
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_stats_mstats_common.py:130: RuntimeWarning: invalid value encountered in double_scalars
  slope = r_num / ssxm
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_stats_mstats_common.py:140: RuntimeWarning: invalid value encountered in sqrt
  t = r * np.sqrt(df / ((1.0 - r + TINY)*(1.0 + r + TINY)))
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\17810\Impulcifer\venv\lib\site-packages\scipy\stats\_stats_mstats_common.py:142: RuntimeWarning: invalid value encountered in double_scalars
  sterrest = np.sqrt((1 - r**2) * ssym / ssxm / df)
Traceback (most recent call last):
  File "impulcifer.py", line 556, in <module>
    main(**create_cli())
  File "impulcifer.py", line 84, in main
    write_readme(os.path.join(dir_path, 'README.md'), hrir, fs)
  File "impulcifer.py", line 417, in write_readme
    peak_ind, knee_point_ind, noise_floor, window_size = ir.decay_params()
  File "C:\Users\17810\Impulcifer\impulse_response.py", line 115, in decay_params
    n = int(len(squared) / self.fs / wd)  # Number of time windows
ValueError: cannot convert float NaN to integer

**Comment by jaakkopasanen** [comment]
Does everything work now as expected? Can the issue be closed?

**Comment by 1781087246** [comment]
> Does everything work now as expected? Can the issue be closed?

sure
