### ISSUE TITLE
Installation Trouble (macOS): failed to import tabulate module

### ISSUE THREAD

**Issue by n1299cb** [jaakkopasanen/Impulcifer#71]
Hi! I have semi-successfully installed the package and set up a virtual environment. When running `python3 impulcifer.py --help` I am receiving a 

"Traceback (most recent call last):
  File "/Users/user/Documents/Impulcifer/impulcifer.py", line 6, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'"

message in terminal. Is there something that I may be overlooking?

**Comment by jaakkopasanen** [comment]
Hello. Sounds like the package installation wasn't completed successfully. The `requirements.txt` does have tabulate specified, so it should get installed.

Maybe try again and if it doesn't work, post logs from `pip install -U -r requirements.txt` command.

**Comment by n1299cb** [comment]
Hi! Thanks so much for the reply. On reinstallation attempt I received this log during

"Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (24.2)
(venv)  Impulcifer % pip install -U -r requirements.txt
Collecting git+https://github.com/jaakkopasanen/autoeq-pkg@1.2.5#autoeq (from -r requirements.txt (line 8))
  Cloning https://github.com/jaakkopasanen/autoeq-pkg (to revision 1.2.5) to /private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-req-build-gtxz3f_5
  Running command git clone --filter=blob:none --quiet https://github.com/jaakkopasanen/autoeq-pkg /private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-req-build-gtxz3f_5
  Running command git checkout -q 75920c0cfcb7abf52d90f661c27e5e955a5475ef
  Resolved https://github.com/jaakkopasanen/autoeq-pkg to commit 75920c0cfcb7abf52d90f661c27e5e955a5475ef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting matplotlib~=3.3.3 (from -r requirements.txt (line 1))
  Downloading matplotlib-3.3.4.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 7.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      <string>:32: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************
      
      !!
      Traceback (most recent call last):
        File "/Users/user/Documents/Impulcifer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/Documents/Impulcifer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/Documents/Impulcifer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-build-env-jhdw1ji9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-build-env-jhdw1ji9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-build-env-jhdw1ji9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-build-env-jhdw1ji9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-install-om3dtyud/matplotlib_0d383d805d704414ac5be65c3a08c543/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-install-om3dtyud/matplotlib_0d383d805d704414ac5be65c3a08c543/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-install-om3dtyud/matplotlib_0d383d805d704414ac5be65c3a08c543/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip."

**Comment by jaakkopasanen** [comment]
Thanks. There certainly is an error in the package installation. I see you're using Python 3.9 while the install instructions ask for Python 3.8. Could install Python 3.8 and try with that?

**Comment by n1299cb** [comment]
uninstalled all previous versions of python and used hombrew to install python 3.8.19.

After reinstalling Impulcifer and trying to grab requirements I got this now–maybe wrong version of pip?

christian@Christians-MacBook-Pro Impulcifer % source venv/bin/activate
(venv) christian@Christians-MacBook-Pro Impulcifer % python3 -m pip install -U pip
Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-24.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-24.2
(venv) christian@Christians-MacBook-Pro Impulcifer % pip install -U -r requirements.txt
Collecting git+https://github.com/jaakkopasanen/autoeq-pkg@1.2.5#autoeq (from -r requirements.txt (line 8))
  Cloning https://github.com/jaakkopasanen/autoeq-pkg (to revision 1.2.5) to /private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-req-build-8othgqds
  Running command git clone --filter=blob:none --quiet https://github.com/jaakkopasanen/autoeq-pkg /private/var/folders/f9/rq5n1z5d17q2l09099zbp1900000gn/T/pip-req-build-8othgqds
  Running command git checkout -q 75920c0cfcb7abf52d90f661c27e5e955a5475ef
  Resolved https://github.com/jaakkopasanen/autoeq-pkg to commit 75920c0cfcb7abf52d90f661c27e5e955a5475ef
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting matplotlib~=3.3.3 (from -r requirements.txt (line 1))
  Using cached matplotlib-3.3.4-cp39-cp39-macosx_10_9_x86_64.whl.metadata (5.7 kB)
Collecting numpy~=1.19.5 (from -r requirements.txt (line 2))
  Using cached numpy-1.19.5-cp39-cp39-macosx_10_9_x86_64.whl.metadata (2.0 kB)
Collecting scipy~=1.5.4 (from -r requirements.txt (line 3))
  Using cached scipy-1.5.4-cp39-cp39-macosx_10_9_x86_64.whl.metadata (2.0 kB)
Collecting soundfile~=0.10.2 (from -r requirements.txt (line 4))
  Using cached SoundFile-0.10.3.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl.metadata (11 kB)
Collecting sounddevice~=0.3.14 (from -r requirements.txt (line 5))
  Using cached sounddevice-0.3.15-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.cp37.cp38.cp39.pp27.pp32.pp33.pp34.pp35.pp36.pp37-none-macosx_10_6_x86_64.whl.metadata (1.3 kB)
Collecting nnresample~=0.2.4 (from -r requirements.txt (line 6))
  Using cached nnresample-0.2.4.1-py3-none-any.whl.metadata (352 bytes)
Collecting tabulate~=0.8.5 (from -r requirements.txt (line 7))
  Using cached tabulate-0.8.10-py3-none-any.whl.metadata (25 kB)
Collecting cycler>=0.10 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached kiwisolver-1.4.5-cp39-cp39-macosx_10_9_x86_64.whl.metadata (6.4 kB)
Collecting pillow>=6.2.0 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached pillow-10.4.0-cp39-cp39-macosx_10_10_x86_64.whl.metadata (9.2 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.1 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting cffi>=1.0 (from soundfile~=0.10.2->-r requirements.txt (line 4))
  Using cached cffi-1.17.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (1.5 kB)
Collecting pillow>=6.2.0 (from matplotlib~=3.3.3->-r requirements.txt (line 1))
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas~=1.2.0 (from autoeq==1.2.5->-r requirements.txt (line 8))
  Using cached pandas-1.2.5-cp39-cp39-macosx_10_9_x86_64.whl.metadata (4.7 kB)
INFO: pip is looking at multiple versions of autoeq to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0 (from autoeq) (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2)
ERROR: No matching distribution found for tensorflow~=2.4.0
